In [29]:
%load_ext autoreload
%autoreload 2
import sys
from pathlib import Path
path = str(Path.cwd().parent)
print(path)
sys.path.insert(1, path)

import numpy as np
import pandas as pd
import skforecast

print(skforecast.__version__)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/joaquin/Documents/GitHub/skforecast
0.21.0

In [30]:
from skforecast.foundational import FoundationalModels
from skforecast.plot import plot_prediction_intervals
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Single series without exogenous variables

In [31]:
air_passengers = np.array([
    112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118,
    115, 126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140,
    145, 150, 178, 163, 172, 178, 199, 199, 184, 162, 146, 166,
    171, 180, 193, 181, 183, 218, 230, 242, 209, 191, 172, 194,
    196, 196, 236, 235, 229, 243, 264, 272, 237, 211, 180, 201,
    204, 188, 235, 227, 234, 264, 302, 293, 259, 229, 203, 229,
    242, 233, 267, 269, 270, 315, 364, 347, 312, 274, 237, 278,
    284, 277, 317, 313, 318, 374, 413, 405, 355, 306, 271, 306,
    315, 301, 356, 348, 355, 422, 465, 467, 404, 347, 305, 336,
    340, 318, 362, 348, 363, 435, 491, 505, 404, 359, 310, 337,
    360, 342, 406, 396, 420, 472, 548, 559, 463, 407, 362, 405,
    417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390, 432
], dtype=np.float64)
dates = pd.date_range(start='1949-01', periods=len(air_passengers), freq='MS')
data = pd.Series(air_passengers, index=dates, name = "y")

In [32]:
model = FoundationalModels(model="autogluon/chronos-2-small")
_ = model.fit(data)

In [33]:
pred = model.predict(steps=12)
pred

1961-01-01    454.997437
1961-02-01    431.381775
1961-03-01    505.188171
1961-04-01    503.226135
1961-05-01    513.081116
1961-06-01    583.401184
1961-07-01    662.404236
1961-08-01    663.358398
1961-09-01    565.503967
1961-10-01    486.212830
1961-11-01    418.705811
1961-12-01    467.800812
Freq: MS, Name: y, dtype: float32

In [34]:
pred_interval = model.predict(steps=12, quantiles=[0.05, 0.95])
pred_interval

                q_0.05      q_0.95
1961-01-01  423.379761  484.590363
1961-02-01  399.327576  457.483276
1961-03-01  474.193848  534.536621
1961-04-01  469.450867  535.619385
1961-05-01  479.738190  551.826904
1961-06-01  536.951172  626.258850
1961-07-01  607.850342  715.415161
1961-08-01  607.233704  715.351440
1961-09-01  514.448425  611.311157
1961-10-01  450.214417  531.192444
1961-11-01  377.535889  457.886108
1961-12-01  430.162598  506.046021

## Single series with exogenous variables

Chronos-2 accepts past covariates (historical exog aligned to the training series) and future covariates (known values for the forecast horizon). Pass them via the `exog` argument of `fit` and `predict` respectively.

In [35]:
# Synthetic past covariate: scaled month index, aligned with training data
exog_past = pd.DataFrame(
    {"month": data.index.month},
    index=data.index,
)
# Future covariate: known month values for forecast horizon
future_idx = pd.date_range(start="1961-01", periods=12, freq="MS")
exog_future = pd.DataFrame({"month": future_idx.month}, index=future_idx)
exog_future.head()

            month
1961-01-01      1
1961-02-01      2
1961-03-01      3
1961-04-01      4
1961-05-01      5

In [36]:
model_exog = FoundationalModels(model="autogluon/chronos-2-small")
model_exog.fit(series=data, exog=exog_past)
pred = model_exog.predict(steps=12, exog=exog_future)
pred

1961-01-01    454.883850
1961-02-01    434.679932
1961-03-01    502.573395
1961-04-01    503.326691
1961-05-01    521.233887
1961-06-01    591.073547
1961-07-01    673.816162
1961-08-01    672.544861
1961-09-01    573.832275
1961-10-01    491.666016
1961-11-01    426.689880
1961-12-01    475.347107
Freq: MS, Name: y, dtype: float32

## Multi-series

Pass a wide `pd.DataFrame` (each column is one series) to `fit`. `predict` returns a wide `pd.DataFrame` for point forecasts, or a `dict[str, pd.DataFrame]` for quantile forecasts.

In [37]:
# Two related time series: air passengers + a scaled variant
data_s2 = data * 1.2 + 50
data_s2.name = "series_2"
series_wide = pd.DataFrame({"series_1": data, "series_2": data_s2})
series_wide.tail(3)

            series_1  series_2
1960-10-01     461.0     603.2
1960-11-01     390.0     518.0
1960-12-01     432.0     568.4

In [38]:
model_ms = FoundationalModels(model="autogluon/chronos-2-small")
model_ms.fit(series_wide)
pred = model_ms.predict(steps=12)
pred

               level        pred
1961-01-01  series_1  454.997437
1961-01-01  series_2  595.996887
1961-02-01  series_1  431.381775
1961-02-01  series_2  567.658142
1961-03-01  series_1  505.188171
1961-03-01  series_2  656.225708
1961-04-01  series_1  503.226135
1961-04-01  series_2  653.871338
1961-05-01  series_1  513.081116
1961-05-01  series_2  665.697327
1961-06-01  series_1  583.401245
1961-06-01  series_2  750.081543
1961-07-01  series_1  662.404236
1961-07-01  series_2  844.885132
1961-08-01  series_1  663.358398
1961-08-01  series_2  846.030151
1961-09-01  series_1  565.503906
1961-09-01  series_2  728.604614
1961-10-01  series_1  486.212830
1961-10-01  series_2  633.455444
1961-11-01  series_1  418.705811
1961-11-01  series_2  552.446899
1961-12-01  series_1  467.800781
1961-12-01  series_2  611.360962

In [39]:
pred_ms_q = model_ms.predict(steps=12, quantiles=[0.1, 0.9])
pred_ms_q

               level       q_0.1       q_0.9
1961-01-01  series_1  432.167084  476.960449
1961-01-01  series_2  568.600464  622.352539
1961-02-01  series_1  408.762573  452.258423
1961-02-01  series_2  540.515137  592.710083
1961-03-01  series_1  483.700043  527.173401
1961-03-01  series_2  630.440002  682.608032
1961-04-01  series_1  478.806396  525.660950
1961-04-01  series_2  624.567627  680.793152
1961-05-01  series_1  488.363281  539.537964
1961-05-01  series_2  636.035889  697.445557
1961-06-01  series_1  549.081116  614.962280
1961-06-01  series_2  708.897461  787.954590
1961-07-01  series_1  624.234985  702.174927
1961-07-01  series_2  799.081909  892.609985
1961-08-01  series_1  622.848877  701.975464
1961-08-01  series_2  797.418579  892.370605
1961-09-01  series_1  528.405518  597.650513
1961-09-01  series_2  684.086548  767.180664
1961-10-01  series_1  461.143127  519.114380
1961-10-01  series_2  603.371826  672.937378
1961-11-01  series_1  389.129913  450.182434
1961-11-01  series_2  516.955872  590.218872
1961-12-01  series_1  440.973022  496.067078
1961-12-01  series_2  579.167664  645.280518

## Multi-series with exogenous variables

A single `pd.DataFrame` exog is broadcast to all series. Alternatively, pass a `dict[str, pd.DataFrame | None]` to supply per-series past covariates (series absent from the dict or mapped to `None` receive no covariates).

In [40]:
# Shared past covariate broadcast to all series
model_ms_exog = FoundationalModels(model="autogluon/chronos-2-small")
model_ms_exog.fit(series_wide, exog=exog_past)
pred_ms_exog = model_ms_exog.predict(steps=12, exog=exog_future)
pred_ms_exog  # wide pd.DataFrame

               level        pred
1961-01-01  series_1  454.883850
1961-01-01  series_2  595.860718
1961-02-01  series_1  434.679901
1961-02-01  series_2  571.615906
1961-03-01  series_1  502.573547
1961-03-01  series_2  653.088257
1961-04-01  series_1  503.326904
1961-04-01  series_2  653.992310
1961-05-01  series_1  521.233826
1961-05-01  series_2  675.480591
1961-06-01  series_1  591.073425
1961-06-01  series_2  759.288208
1961-07-01  series_1  673.816284
1961-07-01  series_2  858.579712
1961-08-01  series_1  672.544861
1961-08-01  series_2  857.053955
1961-09-01  series_1  573.832092
1961-09-01  series_2  738.598633
1961-10-01  series_1  491.666077
1961-10-01  series_2  639.999329
1961-11-01  series_1  426.689880
1961-11-01  series_2  562.027893
1961-12-01  series_1  475.347168
1961-12-01  series_2  620.416626

In [41]:
# Per-series exog dict: only "y" has a covariate, "y2" does not
model_ms_exog2 = FoundationalModels(model="autogluon/chronos-2-small")
model_ms_exog2.fit(series_wide, exog={"y": exog_past, "y2": None})
pred_ms_exog2 = model_ms_exog2.predict(steps=12, exog={"y": exog_future, "y2": None})
pred_ms_exog2

               level        pred
1961-01-01  series_1  454.997437
1961-01-01  series_2  595.996887
1961-02-01  series_1  431.381775
1961-02-01  series_2  567.658142
1961-03-01  series_1  505.188171
1961-03-01  series_2  656.225708
1961-04-01  series_1  503.226135
1961-04-01  series_2  653.871338
1961-05-01  series_1  513.081116
1961-05-01  series_2  665.697327
1961-06-01  series_1  583.401245
1961-06-01  series_2  750.081543
1961-07-01  series_1  662.404236
1961-07-01  series_2  844.885132
1961-08-01  series_1  663.358398
1961-08-01  series_2  846.030151
1961-09-01  series_1  565.503906
1961-09-01  series_2  728.604614
1961-10-01  series_1  486.212830
1961-10-01  series_2  633.455444
1961-11-01  series_1  418.705811
1961-11-01  series_2  552.446899
1961-12-01  series_1  467.800781
1961-12-01  series_2  611.360962